### ISSUE TITLE
do not install dependencies of minitest-chef-handler gem

### ISSUE THREAD

**Issue by fsimmend** [btm/minitest-handler-cookbook#72]
As long as the gem does not gets rereleased, we should install it without dependencies adding 
` options '--ignore-dependencies ` to the chef_gem resource.

**Comment by b-dean** [comment]
Is this to keep it from installing a newer chef/ohai? Because I think that is solved by chef/minitest-chef-handler#85 which is in v1.1.0 of minitest-chef-handler

**Comment by fsimmend** [comment]
from my side we can close this as we no longer use this technique to run tests. But currently the handler breaks with chef 12.4.0

**Comment by b-dean** [comment]
You can make the handler work if you change what version of minitest-chef-handler it uses. You can do this in  your `.kitchen.yml` (I often have this sort of thing in the platform).

```yaml
platforms:
- name: ubuntu-12.04
  attributes:
    minitest:
      chef_handler_gem_version: 1.1.0
```

Someone should make a pull request to update the default for this attribute in https://github.com/btm/minitest-handler-cookbook/blob/668c667f38a17ed243771744a8d8f1d81818fcae/attributes/default.rb#L5
